version: "3.10"
services:
  app:
      build:
        context: .
        dockerfile: Dockerfile  # Укажите путь к вашему Dockerfile
      volumes:
        - .:/fastapi_app  # Монтируем текущую директорию в контейнер
      ports:
        - "9000:8000"  # Пробрасываем порт 8000 на локальную машину
      environment:
        - ENVIRONMENT=development  # Пример переменной окружения
      depends_on:
        - data_base  # Указываем, что приложение зависит от базы данных

  data_base:
    image: postgres:16
    container_name: breakfast_news
    command: -p 5433
    expose:
      - 5433
    env_file:
      - .env-no-dev
    ports:
      - 5433:5433

