version: '3.8'

services:
  db:
    image: postgres:latest  # Используем официальный образ PostgreSQL
    restart: always
    environment:
      POSTGRES_USER: developer  # Укажите имя пользователя
      POSTGRES_PASSWORD: root  # Укажите пароль
      POSTGRES_DB: BreakFast_News  # Имя базы данных
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Для хранения данных
    ports:
      - "5432:5432"  # Пробрасываем порт для доступа к базе данных

  backend:
    build:
      context: ./app  # Укажите путь к вашему бэкенду
    restart: always
    depends_on:
      - db  # Указываем, что бэкенд зависит от базы данных
    environment:
      DATABASE_URL: postgres://developer:yourpassword@db:5432/BreakFast_News  # Строка подключения к базе данных
    ports:
      - "8000:8000"  # Пробрасываем порт для доступа к бэкенду